// Package template 提供代码生成的模板定义和辅助函数
package template

import (
	"strings"
	"text/template"
)

// LogFieldsTemplate 是生成日志字段代码的模板字符串
const LogFieldsTemplate = `// Code generated by gologfields; DO NOT EDIT.
package {{ .PackageName }}

import (
	"github.com/zeromicro/go-zero/core/logx"
)

// fieldKeys 日志字段名常量（与类型名保持一致）
var fieldKeys = struct {
{{- range .Fields }}
	{{ .Name }} string
{{- end }}
}{
{{- range .Fields }}
	{{ .Name }}: "{{ .JSONName }}",
{{- end }}
}

{{- range .Fields }}

// {{ .Name }} {{ .Comment }}
type {{ .Name }} {{ .Type }}

// W{{ .Name }} 创建{{ .Comment }}日志字段
func W{{ .Name }}(v {{ .Type }}) logx.LogField {
	return logx.Field(fieldKeys.{{ .Name }}, {{ .Name }}(v))
}
{{- if .Mask }}

// MaskSensitive 实现 Sensitive 接口，对{{ .Comment }}进行脱敏
func (v {{ .Name }}) MaskSensitive() any {
	return mask{{ .Name }}({{ .Type }}(v))
}
{{- end }}
{{- end }}
`

// ToPascal 将 snake_case 转换为 PascalCase
func ToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

// ToLower 将字符串转换为小写
func ToLower(s string) string {
	return strings.ToLower(s)
}

// FuncMap 返回模板函数映射
func FuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascal": ToPascal,
		"toLower":  ToLower,
	}
}
